name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: 3o14/package-lock.json

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 📦 Install dependencies
        run: npm install
        working-directory: 3o14

      - name: 👷 Build APK
        run: |
          eas build --local \
            --non-interactive \
            --output=./app-build.apk \
            --platform=android \
            --profile=production
        working-directory: 3o14

      - name: 🚀 Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: 3o14/app-build.apk
          tag_name: release-${{ github.sha }}
          name: Android APK Release
          body: "Automated build for commit ${{ github.sha }}"
          draft: false
          prerelease: false

      - name: ✅ Clean up build artifacts
        run: rm -rf 3o14/app-build.apk
