name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: 3o14/package-lock.json

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 📦 Install dependencies
        run: npm install
        working-directory: 3o14

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Extract version from app.json
        id: get_version
        run: echo "version=$(jq -r .version 3o14/app.json)" >> $GITHUB_ENV

      - name: 👷 Build APK
        run: |
          eas build --local \
            --non-interactive \
            --output=./app-build.apk \
            --platform=android \
            --profile=production
        working-directory: 3o14

      - name: 🚀 Upload APK to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 3o14/app-build.apk
          tag: v${{ env.version }}
          name: 3o14 v${{ env.version }}
          body: "Automated build for version ${{ env.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Clean up build artifacts
        run: rm -rf 3o14/app-build.apk
